config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  resources :tweets, only: [:create]

  get :dashboard, to: 'dashboard#index'

  resources :usernames, only: [:new, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :body, presence: true, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: { case_sensitive: false }, allow_blank: true

  before_save :set_display_name, if: -> { username.present? && display_name.blank? }
  def set_display_name
    self.display_name = username.humanize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :redirect_to_username_form, if: -> { user_signed_in? && current_user.username.blank? }

  protected

  def after_sign_in_path_for(resource)
    dashboard_path
  end

  def redirect_to_username_form
    # return if controller_name == 'usernames'
    redirect_to new_username_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @tweets = Tweet.includes(:user).order(created_at: :desc).map { |tweet| TweetPresenter.new(tweet) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      respond_to do |format|
        format.html { redirect_to dashboard_path }
        format.turbo_stream
      end
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body).merge(user: current_user)
  end
end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :redirect_to_username_form
  def new

  end

  def update
    if username_params[:username].present? && current_user.update(username_params)
      flash[:notice] = "username successfully updated."
      redirect_to dashboard_path
    else
      flash[:alert] = if username_params[:username].blank?
                        "please set a username"
                      else
                        current_user.errors.full_messages.join(', ')
                      end
      redirect_to new_username_path
    end
  end

  private

  def username_params
    params.require(:user).permit(:username, :display_name, :avatar)
  end

end

app/views/dashboard/index.html.erb
<div class="col-7">
  <div class="mb-3">
    <%= link_to "Home", dashboard_path, class: "fs-4 text-decoration-none text-black fw-semibold " %>
  </div>
  <div class="mb-4">
    <%= render "devise/shared/tweet_form" %>
  </div>
  <div id="tweets">
      <%= render partial: "tweets/tweet", collection: @tweets, as: :tweet_presenter %>
  </div>
</div>
<div class="col">
  column
</div>

app/views/home/index.html.erb
<h1>Hello world!</h1>
<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
<%= link_to "Log in", new_user_session_path, class:"btn btn-outline-primary btn-lg" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('twitter.png')%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if flash.any? %>
      <%= render 'devise/shared/flashes' %>
    <% end %>

    <% if user_signed_in? %>
      <% if controller_name == 'usernames' %>
        <%= yield %>
      <% else %>
        <div class="container py-2">
          <div class="row">
            <%= render 'devise/shared/sidebar' %>
            <%= yield %>
          </div>
        </div>
      <% end %>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet_presenter.tweet) do %>
  <div class="tweet d-flex py-3 px-3">
    <div class="flex-shrink-0">
      <%= cl_image_tag tweet_presenter.avatar.key,
      :aspect_ratio=>"1:1",
      :border=>"1px_solid_rgb:ffffff",
      :gravity=>"face",
      :height=>48,
      :quality=>"auto",
      :radius=>"max",
      :width=>48,
      :crop=>"fill",
      :fetch_format=>:auto %>
    </div>

    <div class="flex-grow-1 ms-3">

    <p class="mb-0">
      <span class="fw-bolder"><%= tweet_presenter.display_name %></span>
      <span class="text-muted">
        @<%= tweet_presenter.username %> · <%= tweet_presenter.created_at %></span>
    </p>
    <p><%= tweet_presenter.body %></p>

    <div class="d-flex justify-content-between align-items-center action-links">
      <div class="align-items-center">
        <%= link_to "#",class: "text-decoration-none text-black views" do %>
          <%= image_tag "bar-graph.png", size: "20x20", class: "me-1" %>
          <span>
            Views
          </span>
        <% end %>
      </div>
      <div >
        <%= link_to "#",class: "text-decoration-none text-black replies" do %>
          <%= image_tag "message.png", size: "20x20", class: "me-1" %>
          <span>
            Replies
          </span>
        <% end %>
      </div>
      <div >
        <%= link_to "#",class: "text-decoration-none text-black retweets" do %>
          <%= image_tag "retweet.png", size: "20x20", class: "me-1" %>
          <span>
            retweets
          </span>
        <% end %>
      </div>
      <div >
        <%= link_to "#",class: "text-decoration-none text-black likes" do %>
          <%= image_tag "heart-unfilled.png", size: "20x20", class: "me-1" %>
          <span>
            Likes
          </span>
        <% end %>
      </div>
      <div class="btn-group">
          <%= link_to "#", class: "text-decoration-none text-black bookmark" do %>
          <%= image_tag "bookmark.png", size: "20x20", class: "me-1" %>
          <span>
            Bookmark
          </span>
        <% end %>
      </div>
    </div>
    </div>
  </div>
<% end %>

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.prepend "tweets" do %>
  <%= render partial: "tweets/tweet", locals: { tweet_presenter: TweetPresenter.new(@tweet) } %>
<% end %>

app/views/usernames/new.html.erb
<div class="container py-5" style="max-width: 540px">

  <h2>Set your username</h2>

  <%= form_with model: current_user, local: true, url: username_path(current_user) do |f| %>
  <div class="mb-3">
    <%= f.label :username, class: "form-label" %>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :display_name, class: "form-label" %>
    <%= f.text_field :display_name, class: "form-control" %>
  </div>

  <div class="input-group mb-3">
    <%= f.label :avatar, class: "input-group-text" %>
    <%= f.file_field :avatar, class: "form-control" %>
  </div>

  <%= f.submit "Set username", class: "btn btn-primary btn-twitter rounded-pill" %>
  <% end %>
</div>